---

- name: "Griffin - Create a new database with name '{{ hm_griffin__dbname }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_db:
    name: "{{ hm_griffin__dbname }}"

- name: "Griffin - Add TimescaleDB extension to database '{{ hm_griffin__dbname }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_ext:
    name: timescaledb
    db: "{{ hm_griffin__dbname }}"
    cascade: true

- name: "Griffin - Creating user '{{ hm_griffin__dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_user:
    db: "{{ hm_griffin__dbname }}"
    name: "{{ hm_griffin__dbuser }}"
    password: "{{ hm_griffin__dbpswd }}"
    encrypted: yes
    priv: CONNECT
    role_attr_flags: "NOSUPERUSER,NOCREATEROLE,NOCREATEDB,NOREPLICATION"
    state: present
    login_user: "{{ hm_pgsql__user }}"

# GRANT ALL PRIVILEGES ON DATABASE {{ hm_griffin__dbname }} TO {{ hm_griffin__dbuser }}"
- name: "Griffin - Grant privileges to '{{ hm_griffin__dbname }}' to user '{{ hm_griffin__dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    objs: "{{ hm_griffin__dbname }}"
    role: "{{ hm_griffin__dbuser }}"
    grant_option: yes

# ALTER DEFAULT PRIVILEGES ON DATABASE {{ hm_griffin__dbname }} TO {{ hm_griffin__dbuser }}
- name: "Griffin - Alter default privileges to '{{ hm_griffin__dbname }}' to user '{{ hm_griffin__dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_privs:
    db: "{{ hm_griffin__dbname }}"
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: "{{ hm_griffin__dbuser }}"
    grant_option: yes

#------------------------------------------------------------------------------

- name: Configuring local Telegraf
  template:
    src: "{{ item }}"
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.griffin/telegraf.conf.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/telegraf.conf.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/telegraf.conf.j2"
    - "inventory/group_files/servers/honzamach.griffin/telegraf.conf.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.griffin/telegraf.conf.j2"
    - "telegraf.conf.{{ ansible_lsb['codename'] }}.j2"
    - "telegraf.conf.j2"
  notify:
    - Restart Telegraf service

- name: Ensuring Telegraf service is running and enabled at system start
  service:
    name: telegraf
    state: started
    enabled: yes

#------------------------------------------------------------------------------

- name: "Grafana - Create a new database with name '{{ hm_griffin__grafana_dbname }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_db:
    name: "{{ hm_griffin__grafana_dbname }}"

- name: "Grafana - Creating user '{{ hm_griffin__grafana_dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_user:
    db: "{{ hm_griffin__grafana_dbname }}"
    name: "{{ hm_griffin__grafana_dbuser }}"
    password: "{{ hm_griffin__grafana_dbpswd }}"
    encrypted: yes
    priv: CONNECT
    role_attr_flags: "NOSUPERUSER,NOCREATEROLE,NOCREATEDB,NOREPLICATION"
    state: present
    login_user: "{{ hm_pgsql__user }}"

# GRANT ALL PRIVILEGES ON DATABASE {{ hm_griffin__grafana_dbname }} TO {{ hm_griffin__grafana_dbuser }}"
- name: "Grafana - Grant privileges to '{{ hm_griffin__grafana_dbname }}' to user '{{ hm_griffin__grafana_dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    objs: "{{ hm_griffin__grafana_dbname }}"
    role: "{{ hm_griffin__grafana_dbuser }}"
    grant_option: yes

# ALTER DEFAULT PRIVILEGES ON DATABASE {{ hm_griffin__grafana_dbname }} TO {{ hm_griffin__grafana_dbuser }}
- name: "Grafana - Alter default privileges to '{{ hm_griffin__grafana_dbname }}' to user '{{ hm_griffin__grafana_dbuser }}'"
  become: yes
  become_user: "{{ hm_pgsql__user }}"
  postgresql_privs:
    db: "{{ hm_griffin__grafana_dbname }}"
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: "{{ hm_griffin__grafana_dbuser }}"
    grant_option: yes

- name: Configuring Grafana
  template:
    src: "{{ item }}"
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.griffin/grafana.ini.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/grafana.ini.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/grafana.ini.j2"
    - "inventory/group_files/servers/honzamach.griffin/grafana.ini.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.griffin/grafana.ini.j2"
    - "grafana.ini.{{ ansible_lsb['codename'] }}.j2"
    - "grafana.ini.j2"
  notify:
    - Restart Grafana service

- name: Configuring Grafana datasources
  template:
    src: "{{ item }}"
    dest: /etc/grafana/provisioning/datasources/griffin.yaml
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.griffin/grafanads.griffin.yaml.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/grafanads.griffin.yaml.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.griffin/grafanads.griffin.yaml.j2"
    - "inventory/group_files/servers/honzamach.griffin/grafanads.griffin.yaml.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.griffin/grafanads.griffin.yaml.j2"
    - "grafanads.griffin.yaml.{{ ansible_lsb['codename'] }}.j2"
    - "grafanads.griffin.yaml.j2"
  notify:
    - Restart Grafana service

- name: Ensuring Grafana service is running and enabled at system start
  service:
    name: grafana-server
    state: started
    enabled: yes
