---

- name: Refresh APT cache
  apt:
    update_cache: yes

- name: Restart Telegraf service
  service:
    name: telegraf
    state: restarted

- name: Restart Grafana service
  service:
    name: grafana-server
    state: restarted